#!/usr/bin/env python3
import sys
import os
import subprocess as sp

myArr = sys.argv[:]
fname = None
index = None

for i, k in enumerate(myArr):
    if '.go' in k[-3:]:
        fname = k
        index = i
        break
else:
    print("No .go file found as argument")
    exit(0)

contents = open(fname).read().split('\n')

arr = []
for i, line in enumerate(contents):
    if 'func' in line:
        break
    arr.append(line)

for j, line in enumerate(contents):
    if 'func' in line[:4]:
        line = line.strip()[:-1].strip()
        arr.append(line)

arr += contents[i:]

open('/tmp/myout', 'w').write('\n'.join(arr))
myArr[0] = myArr[0].replace('wrapper', 'bin/ast')
myArr[index] = '/tmp/myout'

sp.call(myArr)

# print(open('out.s').read())

