Symbol table:
2-1-0-m :: int
2-1-0-k :: int
2-1-0-j :: int
2-1-0-a :: int
2-1-0-l :: int
2-1-0-c :: string
ffi :: ffi
2-1-0-f :: int
0-main :: func () ()
fmt :: fmt
2-1-0-d :: int
2-1-0-e :: int
2-1-0-g :: int
2-1-0-h :: int
2-1-0-i :: int

Type table:
ffi :: struct { }
string :: string
fmt :: struct { Hello int; Printf func (string, ) (); IOCall func () (string, int, ); }
float :: float
int :: int
void :: void
bool :: bool
byte :: byte
